name: Build firmware for keyboards
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-cli:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        keymap:
          - reviung34
          - tbkmini
          - crkbd
          - ferris_0_1
          - kyria
          - dacmani
          - jd45

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
          submodules: true

      - name: Setup
        id: setup
        run: |
          TARGET="${{ matrix.keymap }}"

          docker run --rm \
            -w /qmk_firmware \
            -v $PWD:/qmk_firmware \
            -e ALT_GET_KEYBOARDS=true \
            qmkfm/qmk_cli \
            /usr/local/bin/qmk setup

      - name: Build
        id: build
        run: |
          TARGET="${{ matrix.keymap }}"

          docker run --rm \
            -w /qmk_firmware \
            -v $PWD:/qmk_firmware \
            -e ALT_GET_KEYBOARDS=true \
            qmkfm/qmk_cli \
            /usr/local/bin/qmk compile -c users/crd/keymaps/${TARGET}.json

          echo ::set-output name=artifact-name::${TARGET//[:<>|*?\\\/]/_}
          echo "Artifact-name: ${{ steps.build.outputs.artifact-name }}"

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "${{ steps.build.outputs.artifact-name }}"
          path: |
            *.hex
            *.bin
        continue-on-error: true
